### ISSUE TITLE
a combination of self-supervised learning and the pretraining

### ISSUE THREAD

**Issue by guava1427** [nilesh0109/self-supervised-semantic-segmentation#1]
Hello, thank you for your blog and this contribution.

I started to study self-supervised learning. I'm curious whether you tried to get the SSL gain from the ImageNet pretrained network. If you tried it, how was the result?

**Comment by nilesh0109** [comment]
Hey , thank you for your comment. Actually i didn't try SSL gain from imageNet pretraining but certainly it could be experimented.
